version: '2'
services:
  origin:
    command: "bin/rails server --port 3000 --bind '0.0.0.0'"
    build:
      context: ./origin
    volumes:
      - ./origin:/usr/lib/origin
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - memcached
    environment:
      - RAILS_ENV
      - ORIGIN_ENCRYPTION_PRIVATE
      - ORIGIN_ENCRYPTION_SALT
      - RAILS_SESSION_PRIVATE
      - ORIGIN_LOCATION
      - WWW_LOCATION
  www:
    command: "npm run start"
    build:
      context: ./www
    volumes:
      - ./www:/usr/lib/www
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV
      - ORIGIN_LOCATION
      - WWW_LOCATION
  postgres:
    image: postgres:9.6.0
    ports:
      - "5432:5432"
  memcached:
    image: memcached
    ports:
      - "11211:11211"
